WINDOW_WIDTH = 1580
WINDOW_HEIGHT = 930

MONITORING_TITLE = "MONITORING"
PLOT_TITLE = "PLOT"
EDITOR_TITLE = "EDITOR"
INFORMATION_TITLE = "INFORMATION"
SETTING_TITLE = "SETTING"
PROCESS_STR = "PROCESS INFORMATION :I.D.8"
SPOOLER_STR = "SPOOLER"
UTILITY_STR = "UTILITY"


INFO_TITLE_WIDTH = 25
COUNTER_TITLE_WIDTH = 20
FONT_SIZE_LARGE = 14
FONT_SIZE_NORMAL = 12
FONT_SIZE_SMALL = 8
FONT_NAME_LARGE = 'TkDefaultFont'
FONT_NAME_NORMAL = FONT_NAME_LARGE
FONT_NAME_SMALL = FONT_NAME_LARGE

REAL_TIME_DATA_FONT = ("Purisa",14,"bold")

REAL_TIME_DATA_FONT_SMALL = ("Purisa",10,"bold")

TAB_FONT = "TkDefaultFont 10"

RPOCESS_INFO_VALUE_FG = 'blue'

BACKGROUNND = '#558ED5'
SPOOLER_VIEW_BG = '#CCECFF'
RPOCESS_HEADER_BG = 'gray'
BAR_RED = '#FC4141'
BAR_YELLOW = '#FFC000'
BAR_GREEN = '#00CC00'
MECHA_TITLE_BG = '#FFFF66'
MECHA_VALUE_BG ='#FF6600'
BLOCK_SEPARATOR='gray'
REAL_TIME_PRO_TITLE_COLOR = '#709CFF'
REAL_TIME_DATA_BG = '#B9CDE5'
MOTOR_ON_BG = '#28D728'
MOTOR_OFF_BG = '#D00000'
MOTOR_ON_FILL = 'red'
MOTOR_OFF_FILL = 'white'
REAL_TIME_DATA_FILL = '#00B3F0'




SPOOLER_PAD_RIGHT = 225

MONITORING_BAR_WIDTH = 75
MONITORING_BAR_HEIGHT = 20

MOTOR_INFO_BAR_WIDTH = MONITORING_BAR_WIDTH-10
MOTOR_INFO_BAR_HEIGHT = MONITORING_BAR_HEIGHT-8

BLOCK_ID_CANVAS_HEIGHT = 30
#MOTOR_INFO

MONITORING_NB_PAD_X = 20

MONITORING_TITLE_PAD_Y = 10

BLOCK_COUNT = 13

BALL_SHIFT_X = 17

TEMPERATURE_THRESHOLD = 10.0
DENSER_PRESSURE_THRESHOLD = 10.0

# constants used in mqtt connectoin

TOPIC_ALL_DATA = 'KWSA/PRODUCTION_LINE/ALL_DATA'
SERVER_ADDR = '223.171.41.180'    
MAX_BLK = 14

# constants used in mqtt connectoin

# constants related to data

MAX_RPM = 4000.0
MAX_CURRENT = 50.0
MAX_TORQUE = 50.0

DENSER_PRESSURE_LOW = 20.0
DENSER_PRESSURE_HIGHT = 60.0

WIRE_TEMP_LOW = 20.0 
WIRE_TEMP_HIGH = 40.0

DRUM_TEMP_LOW = 20.0
DRUM_TEMP_HIGH = 40.0

DICE_TEMP_LOW = 20.0
DICE_TEMP_HIGH = 40.0


# constants related to data



SIDE_PANEL_WIDTH=120
SIDE_PANEL_BG=REAL_TIME_DATA_BG

MOTOR_INFO_TEXT = "MOTOR INFORMATION"




